[build]
  command = "npm run build:ssr"
  publish = "dist/portfolio/browser"  # Change 'portfolio' to your app name

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/angular-runtime"

  [plugins.inputs]
    ssrTarget = "dist/portfolio/server/main.js"  # Make sure this is correct
